# Generated by Django 5.0.6 on 2024-08-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(default=None, upload_to='chat_avatar/'),
        ),
    ]
